services:
    dev:
        build:
            context: ./vendor/reedware/sail-lite/runtimes/basic
            dockerfile: Dockerfile
            args:
                PHP: '${PHP_VERSION:-8.4}'
                WWWGROUP: '${WWWGROUP}'
        image: laravel-relation-joins
        environment:
            WWWUSER: '${WWWUSER}'
        volumes:
            - '.:/var/www/html'
